package com.stuffapp.protectmyhistory;

import android.app.*;import android.content.*;import android.database.*;import android.net.Uri;import android.os.*;import android.provider.*;import java.util.*;

public class DeviceHistoryService extends Service {
    private final Handler h=new Handler(Looper.getMainLooper()); private long lastSms=0,lastCall=0,lastContact=0;
    private final Runnable poll=new Runnable(){public void run(){scanSms();scanCalls();scanContacts();h.postDelayed(this,15000);}};
    @Override public void onCreate(){super.onCreate();NotificationManager nm=getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel("history","ProtectMyHistory",NotificationManager.IMPORTANCE_LOW));Notification n=new Notification.Builder(this,"history").setSmallIcon(android.R.drawable.ic_menu_recent_history).setContentTitle("ProtectMyHistory is recording").setContentText("Tap the app to review your memory timeline").build();startForeground(71,n);h.post(poll);}
    private void scanSms(){if(checkSelfPermission("android.permission.READ_SMS")!=0)return;try(Cursor c=getContentResolver().query(Uri.parse("content://sms"),new String[]{"date","address","body","type"},"date>?",new String[]{String.valueOf(lastSms)},"date ASC")){while(c!=null&&c.moveToNext()){long d=c.getLong(0);HistoryStore.add(this,c.getInt(3)==2?"TEXT_SENT":"TEXT_RECEIVED","sms",c.getString(1)+" | "+c.getString(2));lastSms=Math.max(lastSms,d);}}catch(Exception ignored){}}
    private void scanCalls(){if(checkSelfPermission("android.permission.READ_CALL_LOG")!=0)return;try(Cursor c=getContentResolver().query(CallLog.Calls.CONTENT_URI,new String[]{CallLog.Calls.DATE,CallLog.Calls.NUMBER,CallLog.Calls.TYPE,CallLog.Calls.DURATION},CallLog.Calls.DATE+">?",new String[]{String.valueOf(lastCall)},CallLog.Calls.DATE+" ASC")){while(c!=null&&c.moveToNext()){long d=c.getLong(0);HistoryStore.add(this,"CALL","dialer",c.getString(1)+" | type="+c.getInt(2)+" | seconds="+c.getLong(3));lastCall=Math.max(lastCall,d);}}catch(Exception ignored){}}
    private void scanContacts(){if(checkSelfPermission("android.permission.READ_CONTACTS")!=0)return;try(Cursor c=getContentResolver().query(ContactsContract.Contacts.CONTENT_URI,new String[]{ContactsContract.Contacts.CONTACT_LAST_UPDATED_TIMESTAMP,ContactsContract.Contacts.DISPLAY_NAME},ContactsContract.Contacts.CONTACT_LAST_UPDATED_TIMESTAMP+">?",new String[]{String.valueOf(lastContact)},ContactsContract.Contacts.CONTACT_LAST_UPDATED_TIMESTAMP+" ASC")){while(c!=null&&c.moveToNext()){long d=c.getLong(0);HistoryStore.add(this,"CONTACT_ADDED_OR_CHANGED","contacts",c.getString(1));lastContact=Math.max(lastContact,d);}}catch(Exception ignored){}}
    @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;} @Override public android.os.IBinder onBind(Intent i){return null;} @Override public void onDestroy(){h.removeCallbacks(poll);super.onDestroy();}
}
