package com.stuffapp.protectmyhistory;

import android.app.*;import android.content.*;import android.net.VpnService;import android.os.ParcelFileDescriptor;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.ConcurrentHashMap;

public final class DomainVpnService extends VpnService {
    public static final String ACTION_START="com.stuffapp.protectmyhistory.START_DNS";
    public static final String ACTION_STOP="com.stuffapp.protectmyhistory.STOP_DNS";
    private static final String CHANNEL="protectmyhistory-dns",UPSTREAM="1.1.1.1",VPN_ADDR="10.77.0.2",VPN_DNS="10.77.0.1";
    private final Map<String,Long> recent=new ConcurrentHashMap<>(); private volatile boolean running; private ParcelFileDescriptor tunnel; private Thread worker;
    @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null&&ACTION_STOP.equals(i.getAction())){shutdown();stopSelf();return START_NOT_STICKY;}channel();startForeground(72,notification());if(!running)startTunnel();return START_STICKY;}
    private void channel(){NotificationManager n=getSystemService(NotificationManager.class);NotificationChannel c=new NotificationChannel(CHANNEL,"ProtectMyHistory DNS",NotificationManager.IMPORTANCE_LOW);c.setDescription("Records standard DNS domain requests on this phone");n.createNotificationChannel(c);}
    private Notification notification(){PendingIntent p=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.ic_lock_lock).setContentTitle("ProtectMyHistory DNS is active").setContentText("Standard domain requests are being recorded").setOngoing(true).setOnlyAlertOnce(true).setContentIntent(p).build();}
    private void startTunnel(){try{tunnel=new Builder().setSession("ProtectMyHistory DNS").setMtu(1500).addAddress(VPN_ADDR,32).addRoute(VPN_DNS,32).addDnsServer(VPN_DNS).setBlocking(true).establish();if(tunnel==null){stopSelf();return;}running=true;worker=new Thread(this::loop,"protectmyhistory-dns");worker.start();}catch(Throwable t){HistoryStore.add(this,"DNS_ERROR","vpn",String.valueOf(t));shutdown();stopSelf();}}
    private void loop(){try(FileInputStream in=new FileInputStream(tunnel.getFileDescriptor());FileOutputStream out=new FileOutputStream(tunnel.getFileDescriptor())){byte[] packet=new byte[32767];while(running){int length=in.read(packet);Parsed q=parse(packet,length);if(q==null)continue;if(!q.domain.isEmpty())log(q.domain);byte[] answer=resolve(q.payload);byte[] response=answer==null?null:response(q,answer);if(response!=null){out.write(response);out.flush();}}}catch(Throwable ignored){}shutdown();}
    private void log(String domain){String app=ForegroundAppResolver.recentApp(this),value=domain.toLowerCase(Locale.US),key=app+'|'+value;long now=System.currentTimeMillis();Long old=recent.get(key);if(old!=null&&now-old<15000)return;recent.put(key,now);if(recent.size()>3000)recent.clear();HistoryStore.add(this,"DNS",app,value);}
    private byte[] resolve(byte[] query){try(DatagramSocket socket=new DatagramSocket()){protect(socket);socket.setSoTimeout(4000);socket.send(new DatagramPacket(query,query.length,InetAddress.getByName(UPSTREAM),53));byte[] b=new byte[4096];DatagramPacket p=new DatagramPacket(b,b.length);socket.receive(p);return Arrays.copyOfRange(p.getData(),p.getOffset(),p.getOffset()+p.getLength());}catch(Throwable t){return null;}}
    private Parsed parse(byte[] p,int length){try{if(length<28||((p[0]>>4)&15)!=4)return null;int ihl=(p[0]&15)*4;if(ihl<20||length<ihl+20||(p[9]&255)!=17||u16(p,ihl+2)!=53)return null;int dnsOffset=ihl+8,dnsLength=Math.min(u16(p,ihl+4)-8,length-dnsOffset);if(dnsLength<12)return null;byte[] dns=Arrays.copyOfRange(p,dnsOffset,dnsOffset+dnsLength),src=Arrays.copyOfRange(p,12,16),dst=Arrays.copyOfRange(p,16,20);return new Parsed(u16(p,ihl),src,dst,dns,qname(dns));}catch(Throwable t){return null;}}
    private String qname(byte[] d){if(d.length<13||u16(d,4)<1)return "";StringBuilder s=new StringBuilder();int pos=12;while(pos<d.length){int n=d[pos++]&255;if(n==0)break;if((n&192)!=0||pos+n>d.length)return "";if(s.length()>0)s.append('.');for(int i=0;i<n;i++){int c=d[pos++]&255;if(c<33||c>126)return "";s.append((char)c);}}return s.toString();}
    private byte[] response(Parsed q,byte[] dns){try{byte[] o=new byte[28+dns.length];o[0]=69;o[8]=64;o[9]=17;put16(o,2,o.length);System.arraycopy(q.dst,0,o,12,4);System.arraycopy(q.src,0,o,16,4);put16(o,10,checksum(o,0,20));put16(o,20,53);put16(o,22,q.srcPort);put16(o,24,dns.length+8);System.arraycopy(dns,0,o,28,dns.length);return o;}catch(Throwable t){return null;}}
    private int checksum(byte[] d,int off,int len){long sum=0;for(int i=off;i<off+len;i+=2){sum+=((d[i]&255)<<8)|(i+1<off+len?d[i+1]&255:0);while((sum&0xffff0000L)!=0)sum=(sum&65535)+(sum>>>16);}return ((int)~sum)&65535;}
    private int u16(byte[] d,int o){return((d[o]&255)<<8)|(d[o+1]&255);}private void put16(byte[] d,int o,int v){d[o]=(byte)(v>>>8);d[o+1]=(byte)v;}
    private synchronized void shutdown(){running=false;try{if(tunnel!=null)tunnel.close();}catch(IOException ignored){}tunnel=null;if(worker!=null&&worker!=Thread.currentThread())worker.interrupt();worker=null;stopForeground(true);}
    @Override public void onRevoke(){shutdown();stopSelf();super.onRevoke();}@Override public void onDestroy(){shutdown();super.onDestroy();}
    private static final class Parsed{final int srcPort;final byte[] src,dst,payload;final String domain;Parsed(int p,byte[] s,byte[] d,byte[] q,String n){srcPort=p;src=s;dst=d;payload=q;domain=n;}}
}
