package com.stuffapp.protectmyhistory;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.Uri;import android.net.VpnService;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
    private TextView log;
    @Override public void onCreate(Bundle b){super.onCreate(b);build();requestPermissions(new String[]{Manifest.permission.READ_CALL_LOG,Manifest.permission.READ_SMS,Manifest.permission.READ_CONTACTS,Manifest.permission.POST_NOTIFICATIONS},44);}
    private void build(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(32,40,32,24);TextView title=t("ProtectMyHistory",28);title.setTextColor(Color.rgb(21,101,192));box.addView(title);box.addView(t("Private memory breadcrumbs stored only on this phone. Password fields are excluded.",16));Button access=button("1. Turn on Accessibility monitoring");access.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));box.addView(access);Button usage=button("2. Allow app-name matching");usage.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS)));box.addView(usage);Button start=button("3. Start calls, texts and contacts history");start.setOnClickListener(v->{startForegroundService(new Intent(this,DeviceHistoryService.class));toast("History monitor started");});box.addView(start);Button dns=button("4. Start DNS/domain history");dns.setOnClickListener(v->startDns());box.addView(dns);Button refresh=button("Refresh timeline");refresh.setOnClickListener(v->refresh());box.addView(refresh);Button share=button("Export timeline");share.setOnClickListener(v->share());box.addView(share);log=t("",13);log.setTextIsSelectable(true);ScrollView s=new ScrollView(this);s.addView(log);box.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(box);refresh();}
    private void startDns(){Intent consent=VpnService.prepare(this);if(consent!=null)startActivityForResult(consent,722);else launchDns();}
    private void launchDns(){Intent i=new Intent(this,DomainVpnService.class).setAction(DomainVpnService.ACTION_START);startForegroundService(i);toast("DNS/domain history started");}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==722&&result==RESULT_OK)launchDns();}
    private TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(8,12,8,12);return v;} private Button button(String s){Button b=new Button(this);b.setText(s);return b;} private void refresh(){String x=HistoryStore.read(this);log.setText(x.isEmpty()?"No history yet. Complete steps 1 and 2 above.":x);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void share(){try{File f=new File(getCacheDir(),"ProtectMyHistory-timeline.tsv");try(FileOutputStream o=new FileOutputStream(f)){o.write(HistoryStore.read(this).getBytes(StandardCharsets.UTF_8));}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/tab-separated-values");i.putExtra(Intent.EXTRA_TEXT,HistoryStore.read(this));startActivity(Intent.createChooser(i,"Export history"));}catch(Exception e){toast("Export failed: "+e.getMessage());}}
}
